#
# Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2016-2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

spring:

  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      enabled: false
  
  flyway:
    locations:
      - classpath:db/migration/mysql
      - classpath:db/migration/prod
  
  datasource:
    url: jdbc:mysql://${IAM_DB_HOST:dev.local.io}:${IAM_DB_PORT:3306}/${IAM_DB_NAME:iam}?useSSL=${IAM_DB_USE_SSL:false}
    username: ${IAM_DB_USERNAME:iam}
    password: ${IAM_DB_PASSWORD:pwd}
    
    hikari:
      maximum-pool-size: ${IAM_DB_MAX_ACTIVE:50}
      minimum-idle: ${IAM_DB_MIN_IDLE:8}
      connection-test-query: ${IAM_DB_VALIDATION_QUERY:SELECT 1}