ALTER TABLE iam_x509_cert DROP CONSTRAINT IF EXISTS CONSTRAINT_32;
ALTER TABLE iam_x509_cert DROP CONSTRAINT IF EXISTS UNIQ_IAM_X509_CERT_CERIFICATE;
CREATE INDEX idx_subject_dn ON iam_x509_cert(subject_dn);