#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.h2.server.web=DEBUG
#logging.level.org.springframework.security.web.FilterChainProxy=TRACE
#logging.level.org.springframework.security.oauth2.server.authorization=TRACE