CREATE TABLE IF NOT EXISTS iam_federated_client (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
	
	client_id VARCHAR(256),
	client_secret VARCHAR(2048),
	
	client_name VARCHAR_IGNORECASE(256),
	token_endpoint_auth_method VARCHAR(256),

	jwks_uri VARCHAR(2048),
	jwks VARCHAR(8192),
	
	created_at TIMESTAMP,
	active BOOLEAN,
	
	expiration TIMESTAMP NOT NULL,
    entity_id VARCHAR(512) NOT NULL,
	
	UNIQUE (entity_id)
);

CREATE TABLE IF NOT EXISTS iam_federated_client_redirect_uri (
    owner_id VARCHAR(256),
    redirect_uri VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS iam_federated_client_grant_type (
    owner_id VARCHAR(256),
    grant_type VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS iam_federated_client_response_type (
    owner_id VARCHAR(256),
    response_type VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS iam_federated_client_scope (
    owner_id VARCHAR(256),
    scope VARCHAR(2048)
);