
CREATE TABLE IF NOT EXISTS iam_client_last_used (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
  client_id BIGINT NOT NULL,
  last_used TIMESTAMP NOT NULL);

ALTER TABLE iam_client_last_used ADD CONSTRAINT fk_iam_client_last_used_client_id FOREIGN KEY (client_id) REFERENCES client_details(id);
