server {
  listen 80;
  listen [::]:80;
  server_name _;

  location /bundles/ {
        alias /usr/share/nginx/html/bundles/;
        autoindex on;
        types {
            application/gzip gz tgz tar.gz;
        }
        default_type application/octet-stream;
        add_header Content-Disposition "attachment";
    }

}