[ iam_remote_io ]

default_bits           = 2048
default_keyfile        = ${ENV::CA_NAME}/certs/iam_remote_io.key.pem
distinguished_name     = iam_remote_io_dn
prompt                 = no
encrypt_key            = no
default_md             = sha512
x509_extensions        = iam_remote_io_extensions
[ iam_remote_io_dn ]

C                      = IT
O                      = IGI
CN                     = iam-remote.local.io

[ iam_remote_io_extensions ]

basicConstraints       = critical,CA:FALSE
subjectKeyIdentifier   = hash
keyUsage               = critical, digitalSignature
extendedKeyUsage       = serverAuth, clientAuth
authorityKeyIdentifier = keyid, issuer
subjectAltName         = DNS:iam-remote.local.io
